name: typings-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Coursier
        run: curl -Lo cs https://git.io/coursier-cli-linux && chmod +x cs
        
      - name: Install Java
        run: eval "$(./cs java --jvm 11 --env)" && java --version

      - name: Install Sbt
        run: java --version && ./cs install sbt-launcher
        
      - name: Compile
        run: ~/.local/share/coursier/bin/sbt compile
        
      - name: Publish
        run: ~/.local/share/coursier/bin/sbt stPublish
