name: typings-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Coursier
        run: curl -Lo cs https://git.io/coursier-cli-linux && chmod +x cs
        
      - name: Install Java
        run: |
          eval "$(./cs java --jvm 11 --env)"
          echo ::set-env name=PATH::~/.local/share/coursier/bin:$PATH

      - name: Install Sbt
        run:  ./cs install sbt-launcher

      - name: Which Sbt
        run:  which sbt && echo $PATH
